use crate::prelude::Days;
use crate::{Packaging, Recipe};

/// Instructions for each major step of the process.
///
/// These instructions can have values substituted in, see the
/// source code file.
#[derive(Debug, Clone, Default)]
pub struct Steps {
    /// Header
    pub header: Vec<String>,

    /// Acquisition
    pub acquire: Vec<String>,

    /// Preparation
    pub prep: Vec<String>,

    /// Mashing
    pub mash: Vec<String>,

    /// The boil
    pub boil: Vec<String>,

    /// Chilling the wort
    pub chill: Vec<String>,

    /// Moving to fermenter and pitching the yeast
    pub pitch: Vec<String>,

    /// Fermenting
    pub ferment: Vec<String>,

    /// Packaging
    pub package: Vec<String>,
}

/// Print a recipe in full detail to a String.
///
/// If you pass in custom_steps, they will be the first steps in each
/// section, followed by the standard steps.
#[must_use]
pub fn print_recipe(recipe: &Recipe, custom_steps: Option<Steps>) -> String {
    let mut steps = match custom_steps {
        Some(steps) => steps,
        None => Default::default(),
    };

    // Local variables for format! substitutions

    let style = recipe.style;
    let time_until_done = recipe.time_until_done();
    let batch_size = recipe.process.ferment_volume;
    let mash_ph = recipe.mash_ph();
    let yeast_cells = recipe.yeast_cells_needed();
    let ibu = recipe.ibu_tinseth();
    let min_ibu = recipe.style.ibu_range().start.0;
    let max_ibu = recipe.style.ibu_range().end.0;
    let color = recipe.color();
    let min_color = recipe.style.color_range().start.0;
    let max_color = recipe.style.color_range().end.0;
    let og = recipe.original_gravity();
    let min_og = recipe.style.original_gravity_range().start.0;
    let max_og = recipe.style.original_gravity_range().end.0;
    let fg = recipe.final_gravity();
    let min_fg = recipe.style.final_gravity_range().start.0;
    let max_fg = recipe.style.final_gravity_range().end.0;
    let abv = recipe.abv();
    let min_abv = recipe.style.abv_range().start;
    let max_abv = recipe.style.abv_range().end;
    let ice_weight = recipe.ice_weight();
    let ice_bath_volume = recipe.chilled_water_volume();
    let total_water_volume = recipe.total_water();
    let water_doses = recipe.water_doses();
    let adjusted_water_profile = recipe.process.adjusted_water_profile();
    let ingredient_list = recipe.ingredient_list_string();
    let strike_volume = recipe.strike_volume();
    let strike_temp = recipe.strike_temperature();
    let infusion_temp = recipe.process.infusion_temperature;
    let sparge_volume = recipe.process.sparge_volume;
    let pre_boil_additions = recipe.pre_boil_additions_string();
    let pre_boil_gravity = recipe.pre_boil_gravity();
    let boil_minutes = recipe.boil_time();
    let hops_additions = recipe.hops_additions_string();
    let whirlfloc = if recipe.fining_desired {
        recipe.whirlfloc_amount()
    } else {
        0.0
    };
    let yeast_nutrient = recipe.yeast_nutrient_amount();
    let post_boil_volume = recipe.process.post_boil_volume();
    let fermentation_temp = recipe.ferment_temperature;
    let yeast = recipe.yeast;
    let fermentation_time = recipe.fermentation_time();
    let lagering_time = recipe.style.recommended_conditioning_time();

    // -- header ------------

    steps.header.push(format!(
        "Recipe for {recipe_name}\n(generated by the beermaker)\n\n",
        recipe_name = &recipe.name,
    ));

    steps.header.push(format!(
        "Specification:\n  \
             Style:            {style}\n  \
             Batch size:       {batch_size}\n  \
             Days:             {time_until_done}\n  \
             Ferment Temp:     {fermentation_temp}\n  \
             Mash pH:          {mash_ph}\n  \
             Yeast Pitch:      {yeast_cells} billion cells\n  \
             Bitterness:       {ibu}   [style: {min_ibu:.1} .. {max_ibu:.1}]\n  \
             Color:            {color}    [style: {min_color:.1} .. {max_color:.1}]\n  \
             Original Gravity: {og} [style: {min_og:.3} .. {max_og:.3}]\n  \
             Final Gravity:    {fg} [style: {min_fg:.3} .. {max_fg:.3}]\n  \
             ABV:              {abv:.1}   [style: {min_abv:.1} .. {max_abv:.1}]\n",
    ));

    steps.header.push(format!(
        "Volume History:\n{}",
        &indent(&recipe.volume_history_string(), 2)
    ));

    // -- acquire ------------

    steps
        .acquire
        .push(format!("Aquire all ingredients:\n\n{ingredient_list}"));

    let mut bits: String = "Acquire sanitizer, iodine (optional), yeast nutrient".to_string();
    if recipe.fining_desired {
        bits.push_str(", whirlfloc, fining agent");
    }
    steps.acquire.push(bits);

    if recipe.process.ice_bath {
        steps.acquire.push(format!(
            "Acquire {ice_weight} of ice. Also place a good part of \
                 {ice_bath_volume} of tap water into refrigerator to chill for \
                 ice bath usage.",
        ));
    }

    steps.acquire.push(format!(
        "Acquire {total_water_volume} of water of the type specified in the \
             recipe."
    ));

    steps.acquire.push(format!(
        "You will need {yeast_cells} billion cells of {yeast}. You may need \
         to start a yeast starter a day before."
    ));

    // -- prep ------------

    steps.prep.push(format!(
        "Dose the full {total_water_volume} of source water as follows:\
             \n{water_doses}\nThis Yields:\n\n{adjusted_water_profile}"
    ));

    steps.prep.push("Calibrate the pH meter.".to_string());

    steps
        .prep
        .push("Clean up the area, make space and clean it.".to_string());

    steps.prep.push(
        "Assemble all equipment for the mash, boil, and ferment including:\n\
         Sanitizer, spray bottle of sanitizer, bowl for sanitizer, \
         scale, thermomemter, pH meter, graduated cylinder, hydrometer, \
         turkey baster, ladel, funnel, timer, fermenter, kettle, kettle lid \
         stirrer, rest for stirrer, mash tun, sparging equipment, \
         boiler for strike/infusion water, etc."
            .to_string(),
    );

    steps
        .prep
        .push("Assemble all ingredients and other materials.".to_string());

    steps
        .prep
        .push("Sanitize equipment now, or during the mash.".to_string());

    // -- mash ------------
    steps.mash.push(format!(
        "Fill the mash tun with {strike_volume} of the treated source water."
    ));

    steps
        .mash
        .push(format!("Bring the strike water up to {strike_temp}"));

    if recipe.mash_rests.len() > 1 {
        steps
            .mash
            .push("Since we are doing a step mash, boil water for step additions.".to_string());
    }

    steps.mash.push("Add the mashable malts.".to_string());

    steps.mash.push("Start the timer.".to_string());

    steps
        .mash
        .push("Stir well, then take the temperature and record it.".to_string());

    steps
        .mash
        .push("Remove a sample and let it cool.".to_string());

    steps.mash.push(
        "Start to prepare sparge water. If you boil it now \
                     it might be cooled enough when sparge happens."
            .to_string(),
    );

    let infusions = recipe.mash_infusions();
    for (i, rest) in recipe.mash_rests.iter().enumerate() {
        let temp = rest.target_temperature;
        let dur = rest.duration;

        if i == 0 {
            steps
                .mash
                .push(format!("Hold the mash at {temp} for {dur}."));
        } else {
            steps.mash.push(format!(
                "Infuse {} of {infusion_temp} into the mash.",
                infusions[i - i]
            ));

            steps
                .mash
                .push(format!("Hold the mash at {temp} for {dur}."));
        }
    }

    steps.mash.push(
        "You can exit the mash early if an iodine test indicates there \
         is no more starch."
            .to_string(),
    );

    steps
        .mash
        .push("Mash out by raising the temperature to 77°C briefly.".to_string());

    steps
        .mash
        .push("Take the pH of the sample that cooled and record it.".to_string());

    steps
        .mash
        .push("Lauter the mash into the boil kettle.".to_string());

    steps.mash.push(format!(
        "Sparge the mash with {sparge_volume} water of about 77°C and let it \
         drain into the boil kettle."
    ));

    // -- boil ------------
    if !recipe.sugars.is_empty() {
        steps.boil.push(format!(
            "Mix into the boil kettle the following sugars:\n\
             \n{pre_boil_additions}"
        ));
    }

    steps.boil.push(format!(
        "Take a sample of the wort into a temperature-safe container \
         and let it cool to below 49°C.  Then measure and record the \
         pre-boil Specific Gravity.  The actual correct gravity \
         can be determined by using the hydrometer_correct binary:\n\
         'cargo run --bin hydrometer_correct'\n\
         The target temp-correct pre-boil gravity is {pre_boil_gravity}"
    ));

    steps
        .boil
        .push("Bring the wort up to a boil.  When it boils, start the boil timer.".to_string());

    steps
        .boil
        .push("Maintain the boil at a rapid rolling boil for the duration.".to_string());

    steps
        .boil
        .push(format!("We will be boiling for {boil_minutes}."));

    steps.boil.push(format!(
        "At various times, add hops:\n\
             \
             {hops_additions}"
    ));

    if recipe.fining_desired {
        steps.boil.push(format!(
            "At 10 minutes before the end of the boil, add \
                 {whirlfloc} whirlfloc tablets."
        ));
    }

    steps.boil.push(format!(
        "At 10 minutes before the end of the boil, add \
             {yeast_nutrient} of yeast nutrient."
    ));

    if recipe.process.ice_bath {
        steps.boil.push(
            "Prepare the ice bath before the boil is complete. \
             Place all the prepared chilled water and ice into the bath."
                .to_string(),
        );
    }

    steps.boil.push(format!(
        "Verify Volume\n\n\
             At this point, make sure the volume is approaching the {post_boil_volume}.\n\n\
             If the volume is too high, you can:\n\
             a) discard some but this will lower the gravity\n\
             b) boil longer, but this will change the hop character\n\n\
             If the volume is too low, you can:\n\
             a) add more boiling water, bring back to a boil briefly.\n\n\
             In any case, write down what happened and so that the recipe can be \
             adjusted for future runs."
    ));

    steps
        .boil
        .push(format!("After {boil_minutes}, turn off the burner."));

    // -- chill ------------

    steps
        .chill
        .push("From this point on, sanitization is important.".to_string());

    steps.chill.push(
        "Rapid chilling is important for multiple reasons to avoid to \
         off-flavors (including DMS), contamination, and drop haze \
         proteins for clarity"
            .to_string(),
    );

    if recipe.process.ice_bath {
        steps.chill.push(
            "Remove the kettle from the stove and dunk into the ice bath to rapidly \
             chill in the ice bath."
                .to_string(),
        );

        steps
            .chill
            .push("Stir the wort. Also stir the ice.".to_string());

        steps
            .chill
            .push("Put the lid on when you are not stirring.".to_string());
    } else {
        steps
            .chill
            .push("Chill the wart according to your setup and equipment".to_string());
    }

    steps
        .chill
        .push("Chill until the temperature gets to 20°C.".to_string());

    steps.chill.push(format!(
        "Original Gravity Reading\n\n\
             When the temperature is down to 20°C, take an Original Gravity reading \
             with the sanitized Glass Graduated Cylinder, Turkey Baster, and Hydrometer. \
             Return the sample after testing. Target is {og}.\n\n\
             If the calculator is needed it is at ( \n\
             'cargo run --bin hydrometer_correct' )."
    ));

    steps.chill.push(format!(
        "Chill further until fermentation temperature is reached, which \
             is {fermentation_temp}"
    ));

    // -- pitch ------------

    steps.pitch.push(format!(
        "Sanitize the fermenter and any equipment used for transfer.",
    ));

    steps
        .pitch
        .push(format!("Transfer the wort into the fermenter.",));

    steps.pitch.push(format!("Oxygenate the wort.",));

    steps
        .pitch
        .push(format!("Verify the temperature is correct for the yeast.",));

    steps
        .pitch
        .push(format!("Pitch {yeast_cells} billion cells of {yeast}.",));

    // -- ferment ------------

    steps
        .ferment
        .push(format!("Close the fermenter and install or setup airlock."));

    steps.ferment.push(format!(
        "Place the fermenter under temperature control. We need it to \
         be and remain at {fermentation_temp} for about {fermentation_time}."
    ));

    steps.ferment.push(format!(
        "Keep an eye on fermentation. At some point it will start to \
         slow down."
    ));

    steps.ferment.push(format!(
        "As soon as it starts to slow, or when gravity is 2-5 points above \
         {fg}, raise the temperature by about 6 to 11°C for a 2 day diacetyl rest."
    ));

    steps.ferment.push(format!(
        "Final Gravity Reading: Measure the final gravity. Return sample to carboy. \
         Target is {fg}",
    ));

    if lagering_time > Days(28) {
        steps.ferment.push(format!(
            "With sanitized equipment, rack off the trub from primary \
             fermenter to a secondary fermenter."
        ));
    }

    if recipe.fining_desired {
        steps.ferment.push(format!("Fining: Add fining agent.",));
    }

    if lagering_time > Days(0) {
        steps.ferment.push(format!(
            "Crash to near 0°C for {lagering_time}. BEWARE, it will want to suck \
             in oxygen as it drops temperature and that will massively oxidize \
             the beer. Replace sanitizer in the airlock with strong alcohol. \
             Use one of these techniques: apply continuous low pressure CO2, \
             use a Co2-filled balloon as the airlock, or use a very long \
             blow-off tube"
        ));
    }

    // -- package ------------

    if let Packaging::Bottle(bottle_volume, sugar) = recipe.process.packaging {
        steps.package.push(format!(
            "Sanitize all equipment including siphon racking cane and tube, bottles, \
	         turkey baster, graduated cylinder, and hydrometer.",
        ));

        steps.package.push(format!(
            "Take second Final Gravity reading. Return the sample to the secondary fermenter."
        ));

        // This is pretty nutty IMHO
        // steps.package.push(format!(
        //"Measure the temperature of the beer, and adjust the priming \
        //sugar quantity, or follow the for the priming sugar \
        //amount (and type).",
        //));

        let total_priming_amount = sugar.priming_amount(
            recipe.style.carbonation_volume(),
            recipe.process.post_ferment_volume(),
            recipe.process.room_temperature,
        );

        steps.package.push(format!(
            "If priming the entire batch at once, which you can do if you are \
             now using a secondary fermenter, or if you use a bottling bucket, \
             then mix in {total_priming_amount} of {sugar}. \
             Try not to oxygenate, but do mix in \
	         the sugar until fully dissolved and distributed.",
        ));

        let bottle_priming_amount = sugar.priming_amount(
            recipe.style.carbonation_volume(),
            bottle_volume,
            recipe.process.room_temperature,
        );

        let num_bottles = (recipe.process.post_ferment_volume().0 / bottle_volume.0).ceil();

        steps.package.push(format!(
            "If priming each bottle separately, add {bottle_priming_amount} \
             of {sugar} to each bottle. Expect to fill up to \
             {num_bottles} bottles.",
        ));

        // This is a bit nutty IMHO too
        //steps.package.push(format!(
        //"Mix in the priming yeast. This should be the same yeast as used \
        //for fermentation, but a small quantity.",
        //));

        steps.package.push(format!(
            "Rack the beer into {num_bottles} {bottle_volume} bottles, capping each one.",
        ));

        steps.package.push(format!(
            "Bottle Conditioning: Leave all bottles at room temperature, in a container \
             that can atch spills, and cover with a towel in case any bottle happens \
             to explode or fountain.  Leave for two weeks."
        ));
    } else {
        let carb_volume = recipe.style.carbonation_volume();
        steps.package.push(format!(
            "Kegging instructions are TBD. Carbonation volume target is {carb_volume}"
        ));
    }

    steps.package.push(format!("The beer is done."));

    // -------------------------------

    let mut output = String::new();

    for block in steps.header.iter() {
        output.push_str(block);
        output.push('\n');
    }
    output.push_str("---ACQUIRE-------------------\n\n");
    for (i, block) in steps.acquire.iter().enumerate() {
        output.push_str(&label("ACQUIRE", i + 1, block));
        output.push('\n');
    }
    output.push_str("---PREP-------------------\n\n");
    for (i, block) in steps.prep.iter().enumerate() {
        output.push_str(&label("PREP", i + 1, block));
        output.push('\n');
    }
    output.push_str("---MASH-------------------\n\n");
    for (i, block) in steps.mash.iter().enumerate() {
        output.push_str(&label("MASH", i + 1, block));
        output.push('\n');
    }
    output.push_str("---BOIL-------------------\n\n");
    for (i, block) in steps.boil.iter().enumerate() {
        output.push_str(&label("BOIL", i + 1, block));
        output.push('\n');
    }
    output.push_str("---CHILL-------------------\n\n");
    for (i, block) in steps.chill.iter().enumerate() {
        output.push_str(&label("CHILL", i + 1, block));
        output.push('\n');
    }
    output.push_str("---PITCH-------------------\n\n");
    for (i, block) in steps.pitch.iter().enumerate() {
        output.push_str(&label("PITCH", i + 1, block));
        output.push('\n');
    }
    output.push_str("---FERMENT-------------------\n\n");
    for (i, block) in steps.ferment.iter().enumerate() {
        output.push_str(&label("FERMENT", i + 1, block));
        output.push('\n');
    }
    output.push_str("---PACKAGE-------------------\n\n");
    for (i, block) in steps.package.iter().enumerate() {
        output.push_str(&label("PACKAGE", i + 1, block));
        output.push('\n');
    }

    output
}

fn label(label: &str, step: usize, s: &str) -> String {
    use std::fmt::Write;
    let mut output = String::new();

    output.push_str(label);
    output.push_str(&format!("-{:02}: ", step));

    let sublines = textwrap::wrap(s, 79 - 9);
    let mut virgin = true;
    for subline in sublines {
        if !virgin {
            write!(output, "{}", " ".repeat(9)).unwrap();
        }
        writeln!(output, "{subline}").unwrap();
        virgin = false;
    }
    output
}

fn indent(s: &str, indent: usize) -> String {
    use std::fmt::Write;
    let mut output = String::new();

    let sublines = textwrap::wrap(s, 79 - indent);
    for subline in sublines {
        write!(output, "{}", " ".repeat(indent)).unwrap();
        writeln!(output, "{subline}").unwrap();
    }
    output
}

fn indent2(s: &str, indent: usize) -> String {
    use std::fmt::Write;
    let mut output = String::new();

    let sublines = textwrap::wrap(s, 79 - indent);
    let mut virgin = true;
    for subline in sublines {
        if !virgin {
            write!(output, "{}", " ".repeat(indent)).unwrap();
        }
        writeln!(output, "{subline}").unwrap();
        virgin = false;
    }
    output
}
